alter table public.players add constraint players_no_prohibited_identity check (lower(trim(display_name)) !~ '^(guest|ghost|anonymous|anon|unknown|player[[:space:]]*[0-9]+)$' and lower(public_slug) !~ '^(guest|ghost|anonymous|anon|unknown|player-[0-9]+)$');

create table private.duplicate_identity_candidates(id uuid primary key default gen_random_uuid(),candidate_player_id uuid not null references public.players,possible_canonical_player_id uuid not null references public.players,status text not null default 'open',created_at timestamptz not null default now(),unique(candidate_player_id,possible_canonical_player_id));

create or replace function public.provision_player_account(p_display_name text,p_public_slug text,p_terms_version text) returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare v_player uuid; begin if auth.uid() is null then raise exception using errcode='P0001',detail='AUTH_REQUIRED'; end if; if not exists(select 1 from auth.users where id=auth.uid() and (email_confirmed_at is not null or phone_confirmed_at is not null)) then raise exception using errcode='P0001',detail='PLAYER_NOT_VERIFIED'; end if; select player_id into v_player from public.accounts where auth_user_id=auth.uid(); if v_player is not null then return v_player; end if; insert into public.players(display_name,public_slug) values(p_display_name,p_public_slug) returning id into v_player; insert into public.accounts(auth_user_id,player_id,contact_verified_at) values(auth.uid(),v_player,now()); insert into private.trust_score_ledger(player_id,reason_code,delta,previous_score,current_score,rule_version,request_id) values(v_player,'account_initialized',0,50,50,'trust-v1',gen_random_uuid()); insert into private.audit_log(actor_auth_user_id,action,aggregate_type,aggregate_id,after_state) values(auth.uid(),'player.provisioned','player',v_player,jsonb_build_object('terms_version',p_terms_version)); return v_player; exception when unique_violation then raise exception using errcode='P0001',detail='ALREADY_EXISTS'; end $$;

create or replace function public.player_ranked_eligible(p_player_id uuid,p_club_id uuid) returns boolean language sql stable security definer set search_path=pg_catalog,public,private as $$ select exists(select 1 from public.accounts a join public.identity_attestations i on i.player_id=a.player_id and i.club_id=p_club_id and i.revoked_at is null join public.clubs c on c.id=p_club_id where a.player_id=p_player_id and a.contact_verified_at is not null and c.subscription_status in ('trialing','active') and (c.subscription_valid_until is null or c.subscription_valid_until>now())) $$;

create or replace function public.attest_player_identity(p_club_id uuid,p_player_id uuid,p_attestation_type text,p_note text,p_idempotency_key uuid) returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare v_id uuid; begin if not private.has_club_role(p_club_id,array['owner','score_official']::public.club_role[]) then raise exception using errcode='P0001',detail='PERMISSION_DENIED'; end if; insert into private.idempotency_commands(actor_id,operation,key,request_hash) values(public.current_player_id(),'attest_player_identity',p_idempotency_key,encode(extensions.digest(concat_ws('|',p_club_id,p_player_id,p_attestation_type,coalesce(p_note,'')),'sha256'),'hex')) on conflict(actor_id,operation,key) do nothing; insert into public.identity_attestations(club_id,player_id,attested_by_player_id,attestation_type,note) values(p_club_id,p_player_id,public.current_player_id(),p_attestation_type,p_note) returning id into v_id; insert into private.audit_log(actor_auth_user_id,action,aggregate_type,aggregate_id,club_id) values(auth.uid(),'identity.attested','player',p_player_id,p_club_id); return v_id; end $$;
revoke all on function public.provision_player_account(text,text,text),public.player_ranked_eligible(uuid,uuid),public.attest_player_identity(uuid,uuid,text,text,uuid) from public;
grant execute on function public.provision_player_account(text,text,text),public.player_ranked_eligible(uuid,uuid),public.attest_player_identity(uuid,uuid,text,text,uuid) to authenticated;
