create or replace function public.current_player_id() returns uuid language sql stable security definer set search_path = pg_catalog, public, private as $$ select player_id from public.accounts where auth_user_id = auth.uid() $$;
create or replace function private.has_club_role(p_club_id uuid, p_roles public.club_role[]) returns boolean language sql stable security definer set search_path = pg_catalog, public, private as $$ select exists(select 1 from public.club_memberships where club_id=p_club_id and player_id=public.current_player_id() and status='active' and role=any(p_roles)) $$;
create or replace function public.is_platform_admin() returns boolean language sql stable security definer set search_path = pg_catalog, public, private as $$ select exists(select 1 from private.platform_admins where auth_user_id=auth.uid()) $$;
revoke all on function public.current_player_id() from public;
grant execute on function public.current_player_id() to authenticated;
revoke all on function public.is_platform_admin() from public;
grant execute on function public.is_platform_admin() to authenticated;
alter table public.players enable row level security;
alter table public.accounts enable row level security;
alter table public.clubs enable row level security;
alter table public.club_memberships enable row level security;
alter table public.identity_attestations enable row level security;
create policy players_public_read on public.players for select using (visibility='public' and merged_into_player_id is null or id=public.current_player_id());
create policy accounts_own_read on public.accounts for select using (auth_user_id=auth.uid());
create policy clubs_public_read on public.clubs for select using (true);
create policy membership_scoped_read on public.club_memberships for select using (player_id=public.current_player_id() or private.has_club_role(club_id,array['owner','organizer','score_official']::public.club_role[]));
grant select on public.players, public.clubs to anon, authenticated;
grant select on public.accounts, public.club_memberships, public.identity_attestations to authenticated;
